Vagrant.configure("2") do |c|
  c.vm.box = "learningchef/centos65"
  c.vm.box_url = "learningchef/centos65"
  c.vm.hostname = "default-centos65.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
